### ISSUE TITLE
What GPU did you use when performing experiments?

### ISSUE THREAD

**Issue by ruizewang** [ChopinSharp/ref-nms#1]
Hi ChopinSharp,
Thanks for your great work. Could you please tell me what GPU you use in this paper?

**Comment by ChopinSharp** [comment]
Hi there. Thanks for your attention. We use GTX1080Ti in our paper. A single one should be suffice.

**Comment by ruizewang** [comment]
Thanks for your quick response. I also have 1080Ti. But when I run the second training script of CM-A-E, (./experiments/scripts/train_erase.sh), I always meet the problem of OOM. I use the default parameters (e.g. batch size=20).
Have you ever meet this problem when you reimplement CM-A-E?

**Comment by ChopinSharp** [comment]
Actually it has been a long time since I last trained the CM-A-E model. I don't quite remember the details. I suggest you check pytorch and cudatoolkit version. Here is my environment for training CM-A-E. (GitHub doesn't support YML files, so a ZIP is uploaded ...)

[cm-a-e.zip](https://github.com/ChopinSharp/ref-nms/files/5824641/cm-a-e.zip)

**Comment by ruizewang** [comment]
Wow, thanks for your help(*^▽^*). It definitely will help me a lot. Now I am going to re-install my environment like yours.

**Comment by ruizewang** [comment]
Hi ChopinSharp, I have installed the same environment as yours, however, I meet the OOM again.
There is the situation:
(1) When I run the first training script of CM-A-E (`./experiments/scripts/train_mattnet.sh`), everything is OK. 
(2) When I run the second training script of CM-A-E (`./experiments/scripts/train_erase.sh`), after some steps, it occurs OOM. I use the default parameters in the script. And the code is run with a single 1080Ti (11G).
I think the default batch size=20 may be too large.  Can you find out what parameters were used to reimplement CM-A-E (one dataset is enough, e.g., on refcoco)?

```
iter[1250](epoch[1]), train_loss=0.280, lr=4.00E-04, data:7.35s/iter, model:0.34s/iter
iter[1275](epoch[1]), train_loss=0.266, lr=4.00E-04, data:7.16s/iter, model:0.34s/iter
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "./tools/train.py", line 340, in <module>
    main(args)
  File "./tools/train.py", line 249, in main
    loss, loss1, loss2, T, wrapped = lossFun(loader, optimizer, model, mm_crit, att_crit, opt, iter)
  File "./tools/train.py", line 126, in lossFun
    loss.backward()
  File "/remote-home/my/anaconda3/envs/matt/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/remote-home/my/anaconda3/envs/matt/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525796793591/work/torch/lib/THC/generic/THCStorage.cu:58
```

**Comment by ChopinSharp** [comment]
You are right. The default batch_size of 20 is too large when training CM-A-E. I used a batch_size of 10 and it turned out all right.

**Comment by ruizewang** [comment]
That makes sense, I got it. Thank you very much.
