### ISSUE TITLE
Question about pseudo ground-truths

### ISSUE THREAD

**Issue by nku-shengzheliu** [ChopinSharp/ref-nms#2]
Hi ChopinSharp!
Thanks for your great work! I have some questions about the generation of pseudo ground-truths for contextual objects. The paper sets γ=0.4 to filter contextual objects, if there are multiple regions after filtering, how to determine which is the correct contexual object? Or do we regard multiple regions after filtering as contextual objects?

**Comment by ChopinSharp** [comment]
Hi there, thanks for your attention!

We regard all regions beyond threshold gamma as pseudo ground-truths. We use pseudo ground-truth to capture context information. So it is normal to have multiple pseudo ground-truths.

**Comment by nku-shengzheliu** [comment]
Got it, thanks for your prompt reply.
